/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2e3038",
        "tertiary-fixed-dim": "#ffb95f",
        "secondary-fixed-dim": "#4edea3",
        "primary-fixed-dim": "#adc6ff",
        "tertiary": "#ffb95f",
        "on-error": "#690005",
        "surface-container": "#1d2027",
        "on-primary": "#002e6a",
        "on-background": "#e1e2ec",
        "surface": "#10131a",
        "on-surface": "#e1e2ec",
        "tertiary-container": "#ca8100",
        "surface-dim": "#10131a",
        "on-primary-fixed-variant": "#004395",
        "surface-container-lowest": "#0b0e15",
        "surface-bright": "#363941",
        "on-tertiary": "#472a00",
        "surface-tint": "#adc6ff",
        error: "#ffb4ab",
        "tertiary-fixed": "#ffddb8",
        "surface-container-high": "#272a31",
        "on-secondary-container": "#00311f",
        "on-error-container": "#ffdad6",
        "outline-variant": "#424754",
        "surface-container-highest": "#32353c",
        background: "#10131a",
        "primary-fixed": "#d8e2ff",
        primary: "#adc6ff",
        "on-primary-container": "#00285d",
        "secondary-fixed": "#6ffbbe",
        "inverse-primary": "#005ac2",
        "on-tertiary-fixed": "#2a1700",
        "secondary-container": "#00a572",
        secondary: "#4edea3",
        "primary-container": "#4d8eff",
        outline: "#8c909f",
        "on-tertiary-container": "#3e2400",
        "on-surface-variant": "#c2c6d6",
        "on-secondary-fixed": "#002113",
        "on-secondary": "#003824",
        "inverse-surface": "#e1e2ec",
        "on-secondary-fixed-variant": "#005236",
        "error-container": "#93000a",
        "surface-variant": "#32353c",
        "on-primary-fixed": "#001a42",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-low": "#191b23",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1440px",
        "panel-padding": "12px",
        unit: "4px",
        margin: "24px",
        gutter: "16px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}